version: '3'
services:
  db:
    image: postgres:13-alpine
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kheina
      POSTGRES_USER: kheina
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kheina -d kheina"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: ./docker/postgres
        target: /etc/postgresql/
  aerospike:
    image: aerospike/aerospike-server:6.4
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    command: [ "--config-file","/etc/aerospike/aerospike.conf"]
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./docker/aerospike
        target: /etc/aerospike/
  backblaze:
    image: ubuntu:latest
    command: [ "--config-file","/etc/aerospike/aerospike.conf"]
    ports:
      - "6000:6000"
    volumes:
      - type: bind
        source: ./docker/backblaze
        target: /etc/backblaze/
