version: '3'
services:
  db:
    image: postgres:13-alpine
    command:
      [
        "postgres",
        "-c",
        "config_file=/etc/postgresql/postgresql.conf"
      ]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kheina
      POSTGRES_USER: kheina
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kheina -d kheina" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: ./docker/postgres
        target: /etc/postgresql/

  aerospike:
    image: aerospike/aerospike-server:6.4
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    command: [ "--config-file", "/etc/aerospike/aerospike.conf" ]
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./docker/aerospike
        target: /etc/aerospike/

  minio:
    image: minio/minio:latest
    command: minio server
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - type: bind
        source: ./docker/minio
        target: /etc/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ADDRESS=:9000
      - MINIO_CONSOLE_ADDRESS=:9090
      - MINIO_VOLUMES=/etc/minio
